name: test inputs

on:
  workflow_dispatch:
    inputs:
      exp_name:
        description: "Optional name for experiment"
        type: string
        required: false
        default: 'direct_experiment'
        
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - run:
        echo 'With space and no caps: ${{ inputs.exp_name }}'
        echo 'no space and no caps: ${{inputs.exp_name}}'
        echo 'With space and caps: ${{ inputs.EXP_NAME }}'
