name: test inputs

on:
  workflow_dispatch:
    inputs:
      exp_name:
        description: "Optional name for experiment"
        type: string
        required: false
        default: 'direct_experiment'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          echo With space and no caps: ${{ github.event.inputs.exp_name }}
          echo no space and no caps: ${{inputs.exp_name}}
          echo With space and caps: ${{ inputs.EXP_NAME }}
